# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Home
email: orlane.lequellennec@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Website page.
twitter_username: username
github_username: orlross
#github: [metadata]
search: true
#baseurl: ""
#url: "https://orlross.github.io/"
#logo: <a href="https://www.flaticon.com/free-icons/rain" title="rain icons">Rain icons created by Freepik - Flaticon</a>


# Build settings
markdown: kramdown
# On peut fixer la version
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

google-site-verification: "rIqJd2ageMYnI6gwwFI2feUJ5LDQqfgK2AmfAh"
# "rIqJd2ageMYnI6gwwFI2feUJ5LDQqfgK2AmfAh-YykI"

# Rajouter les dossiers pour qu'ils soient pris en compte sur le site web
# ["_pages", "_data", "_reminders", "_layouts", "_teachings"]
include: ["_pages", "_teachings", "_data"]

collections:
  # reminders:
  #   output: true
  #   permalink: /:collection/:path/
  teachings:
    output: true
    permalink: /:collection/:path/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
# plugins:
#   - jekyll-paginate
#   - jekyll-sitemap
#   - jekyll-gist
#   - jekyll-feed
#   - jemoji
#   - jekyll-include-cache


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-remote-theme


author:
  name: "Orlane Le Quellennec"
  avatar: "/_data/image/pp.jpg"
  bio: "PhD Student in statistics" # Note: Markdown is allowed
  location: "Montpellier, France"
  email            : "orlane.lequellennec@gmail.com"
  # uri :
  home :  # null (default), "absolute or relative url to link to author home"
  github: "orlross"
  gitlab: "orlane.le-quellennec"
  links:
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/orlane-le-quellennec"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _teachings
  - scope:
      path: ""
      type: teachings
    values:
      layout: single
      author_profile: true
      share: false
      output: true
      toc: true
      toc_label: "Contents"
      toc_icon: "swatchbook"
      sidebar: main
      classes: wide
  # _research
  - scope:
      path: ""
      type: research
    values:
      layout: single
      author_profile: true
      share: false
      output: true
      toc: true
      toc_label: "Contents"
      toc_icon: "swatchbook"
      sidebar: main
      classes: wide
  # cv
  - scope:
      path: ""
      type: cv
    values:
      layout: single
      author_profile: true
      share: false
      output: true
      toc: true
      toc_label: "Contents"
      toc_icon: "swatchbook"
      sidebar: main
      classes: wide


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
